#!/usr/bin/env python3
"""Generate 3D cartridge/disc OBJ models for the NDSUI carousel.

Each cartridge is a proper extruded solid (rounded profile, real thickness,
side walls) with the box art on BOTH faces. Discs are cylinders with a hub
hole, box art on both faces and a rim. Optional per-system silhouette
features: a chamfered corner (DS/3DS/Switch cards), a top notch (GB/GBA),
a grip ridge (N64).

Usage:  python3 tools/gen_models.py <outdir>

Coordinate system: X right, Y up, Z toward viewer (front). Units arbitrary;
the renderer scales to fit the carousel band.
"""
import math
import os
import sys


def rounded_rect(w, h, r, seg=8, corner_cut=None, notch=None):
    """Outline (counter-clockwise) of a rounded rectangle with optional
    features:
      corner_cut = ('tr'|'tl'|'br'|'bl', size)  -> chamfered corner
      notch      = (width, depth)               -> rectangular top notch
    """
    r = min(r, w / 2 - 0.01, h / 2 - 0.01)
    pts = []

    def arc(cx, cy, a0, a1, steps):
        for i in range(steps + 1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))

    # top right corner (optionally cut)
    if corner_cut and corner_cut[0] == "tr":
        s = corner_cut[1]
        pts.append((w / 2 - s, h / 2))
        pts.append((w / 2, h / 2 - s))
        arc(w / 2 - r, h / 2 - r, 0, -90, seg)
    else:
        arc(w / 2 - r, h / 2 - r, 0, 90, seg)

    if notch:
        nw, nd = notch
        x0 = -nw / 2
        pts.append((x0, h / 2))
        pts.append((x0, h / 2 - nd))
        pts.append((x0 + nw, h / 2 - nd))
        pts.append((x0 + nw, h / 2))

    # top left corner
    arc(-(w / 2 - r), h / 2 - r, 90, 180, seg)
    # bottom left
    arc(-(w / 2 - r), -(h / 2 - r), 180, 270, seg)
    # bottom right
    arc(w / 2 - r, -(h / 2 - r), 270, 360, seg)

    # drop duplicates created by the notch joins / arcs
    out = []
    for p in pts:
        if not out or abs(p[0] - out[-1][0]) > 1e-6 or abs(p[1] - out[-1][1]) > 1e-6:
            out.append(p)
    return out


def norm(v):
    l = math.sqrt(sum(c * c for c in v)) or 1.0
    return tuple(c / l for c in v)


class ObjWriter:
    def __init__(self):
        self.v = []
        self.vt = []
        self.vn = []
        self.f = []

    def add_v(self, x, y, z):
        self.v.append((x, y, z))
        return len(self.v)

    def add_vt(self, u, v):
        self.vt.append((u, v))
        return len(self.vt)

    def add_vn(self, x, y, z):
        self.vn.append(norm((x, y, z)))
        return len(self.vn)

    def add_face(self, specs):
        self.f.append(specs)

    def save(self, path):
        with open(path, "w") as fp:
            fp.write("# generated by gen_models.py\n")
            for x, y, z in self.v:
                fp.write(f"v {x:.5f} {y:.5f} {z:.5f}\n")
            for u, v in self.vt:
                fp.write(f"vt {u:.5f} {v:.5f}\n")
            for x, y, z in self.vn:
                fp.write(f"vn {x:.5f} {y:.5f} {z:.5f}\n")
            for specs in self.f:
                fp.write("f " + " ".join(specs) + "\n")


def add_label(o, lw, lh, y, z, normal_sign, nx=4, ny=3):
    """Box-art quad centered at (0,y,z) facing +z/-z, subdivided so the
    (affine) CPU texture mapping does not visibly warp when rotated.
    uv convention: v=0 at the quad's bottom (the renderer flips v once)."""
    lz = z + normal_sign * 0.08
    n = o.add_vn(0, 0, normal_sign)
    u0, u1 = (0, 1) if normal_sign > 0 else (1, 0)
    grid = []
    for iy in range(ny + 1):
        row = []
        fy = iy / ny
        for ix in range(nx + 1):
            fx = ix / nx
            uu = u0 + (u1 - u0) * fx
            vv = fy
            row.append((o.add_v(-lw + 2 * lw * fx, y - lh + 2 * lh * fy, lz),
                        o.add_vt(uu, vv)))
        grid.append(row)
    for iy in range(ny):
        for ix in range(nx):
            a = grid[iy][ix]
            b = grid[iy][ix + 1]
            c = grid[iy + 1][ix + 1]
            d = grid[iy + 1][ix]
            if normal_sign > 0:
                o.add_face([f"{a[0]}/{a[1]}/{n}", f"{b[0]}/{b[1]}/{n}",
                            f"{c[0]}/{c[1]}/{n}", f"{d[0]}/{d[1]}/{n}"])
            else:
                o.add_face([f"{a[0]}/{a[1]}/{n}", f"{d[0]}/{d[1]}/{n}",
                            f"{c[0]}/{c[1]}/{n}", f"{b[0]}/{b[1]}/{n}"])


def add_brand(o, bw, bh, y, z, nx=4):
    """Console-name strip on the front face, below the label. It uses the uv
    range u in [2,3] so the renderer can tell it apart from the label."""
    lz = z + 0.08
    n = o.add_vn(0, 0, 1)
    grid = []
    for iy in range(2):
        row = []
        fy = iy / 1
        for ix in range(nx + 1):
            fx = ix / nx
            row.append((o.add_v(-bw + 2 * bw * fx, y - bh + 2 * bh * fy, lz),
                        o.add_vt(2.0 + fx, fy)))
        grid.append(row)
    for ix in range(nx):
        a = grid[0][ix]
        b = grid[0][ix + 1]
        c = grid[1][ix + 1]
        d = grid[1][ix]
        o.add_face([f"{a[0]}/{a[1]}/{n}", f"{b[0]}/{b[1]}/{n}",
                    f"{c[0]}/{c[1]}/{n}", f"{d[0]}/{d[1]}/{n}"])


def build_cart(w, h, d, r, label_w, label_h, label_off_y=0.0, grip=0.0,
               corner_cut=None, notch=None, seg=9, back_label=False,
               brand=None):
    o = ObjWriter()
    prof = rounded_rect(w, h, r, seg, corner_cut, notch)
    n = len(prof)
    zf, zb = d / 2, -d / 2

    front_ids, back_ids = [], []
    for (x, y) in prof:
        front_ids.append(o.add_v(x, y, zf))
        back_ids.append(o.add_v(x, y, zb))

    nf = o.add_vn(0, 0, 1)
    nb = o.add_vn(0, 0, -1)

    cf = o.add_v(0, 0, zf)
    cb = o.add_v(0, 0, zb)
    for i in range(n):
        j = (i + 1) % n
        o.add_face([f"{cf}//{nf}", f"{front_ids[j]}//{nf}",
                    f"{front_ids[i]}//{nf}"])
        o.add_face([f"{cb}//{nb}", f"{back_ids[i]}//{nb}",
                    f"{back_ids[j]}//{nb}"])

    # side walls (with a soft chamfer: an inset ring near each face)
    for i in range(n):
        j = (i + 1) % n
        x1, y1 = prof[i]
        x2, y2 = prof[j]
        mx, my = (x1 + x2) / 2, (y1 + y2) / 2
        nrm = o.add_vn(mx, my, 0)
        o.add_face([f"{front_ids[i]}//{nrm}", f"{front_ids[j]}//{nrm}",
                    f"{back_ids[j]}//{nrm}", f"{back_ids[i]}//{nrm}"])

    # grip ridge on top (N64 style)
    if grip > 0:
        gw, gh = w * 0.66, grip
        gy = h / 2 + gh * 0.10  # rides the top edge
        gz = d / 2 + 0.20       # sticks out to the front
        p = rounded_rect(gw, gh, min(gw, gh) * 0.30, 4)
        f_ids, b_ids = [], []
        for (x, y) in p:
            f_ids.append(o.add_v(x, y + gy, gz))
            b_ids.append(o.add_v(x, y + gy, gz - 0.15))
        ng = o.add_vn(0, 0, 1)
        cgf = o.add_v(0, gy, gz)
        nn = len(p)
        for i in range(nn):
            j = (i + 1) % nn
            o.add_face([f"{cgf}//{ng}", f"{f_ids[j]}//{ng}", f"{f_ids[i]}//{ng}"])
        for i in range(nn):
            j = (i + 1) % nn
            x1, y1 = p[i]
            x2, y2 = p[j]
            nrm = o.add_vn((x1 + x2) / 2, (y1 + y2) / 2, 0)
            o.add_face([f"{f_ids[i]}//{nrm}", f"{f_ids[j]}//{nrm}",
                        f"{b_ids[j]}//{nrm}", f"{b_ids[i]}//{nrm}"])

    # box art on the front face only (the back stays plain, so rotating the
    # cart never shows a mirrored cover)
    add_label(o, label_w / 2, label_h / 2, label_off_y, d / 2, +1)
    if back_label:
        add_label(o, label_w / 2, label_h / 2, label_off_y, -d / 2, -1)
    if brand:
        bw, bh, by = brand
        add_brand(o, bw / 2, bh / 2, by, d / 2)
    return o


def build_disc(radius, thickness, label_radius, hole=0.55, seg=36,
               back_label=True):
    """Cylinder disc with a hub hole; box art on both faces + rim."""
    o = ObjWriter()
    n = seg
    zt, zb = thickness / 2, -thickness / 2

    top_out, bot_out, top_in, bot_in = [], [], [], []
    uvs = []
    for i in range(n):
        a = 2 * math.pi * i / n
        ca, sa = math.cos(a), math.sin(a)
        top_out.append(o.add_v(radius * ca, radius * sa, zt))
        bot_out.append(o.add_v(radius * ca, radius * sa, zb))
        top_in.append(o.add_v(label_radius * ca, label_radius * sa, zt))
        bot_in.append(o.add_v(label_radius * ca, label_radius * sa, zb))
        uvs.append(o.add_vt(0.5 + 0.5 * ca, 0.5 + 0.5 * sa))

    nup = o.add_vn(0, 0, 1)
    ndn = o.add_vn(0, 0, -1)
    ct = o.add_v(0, 0, zt)
    cb = o.add_v(0, 0, zb)
    uvc = o.add_vt(0.5, 0.5)

    for i in range(n):
        j = (i + 1) % n
        # top: hub + label annulus (box art maps across the disc)
        o.add_face([f"{ct}/{uvc}/{nup}", f"{top_in[j]}/{uvs[j]}/{nup}",
                    f"{top_in[i]}/{uvs[i]}/{nup}"])
        o.add_face([f"{top_in[i]}/{uvs[i]}/{nup}", f"{top_in[j]}/{uvs[j]}/{nup}",
                    f"{top_out[j]}/{uvs[j]}/{nup}", f"{top_out[i]}/{uvs[i]}/{nup}"])
        # bottom
        if back_label:
            o.add_face([f"{cb}/{uvc}/{ndn}", f"{bot_in[i]}/{uvs[i]}/{ndn}",
                        f"{bot_in[j]}/{uvs[j]}/{ndn}"])
            o.add_face([f"{bot_in[i]}/{uvs[i]}/{ndn}", f"{bot_out[i]}/{uvs[i]}/{ndn}",
                        f"{bot_out[j]}/{uvs[j]}/{ndn}", f"{bot_in[j]}/{uvs[j]}/{ndn}"])
        else:
            o.add_face([f"{cb}//{ndn}", f"{bot_out[i]}//{ndn}",
                        f"{bot_out[j]}//{ndn}"])
        # rim
        ca, sa = math.cos(2 * math.pi * i / n), math.sin(2 * math.pi * i / n)
        nrm = o.add_vn(ca, sa, 0)
        o.add_face([f"{top_out[i]}//{nrm}", f"{top_out[j]}//{nrm}",
                    f"{bot_out[j]}//{nrm}", f"{bot_out[i]}//{nrm}"])
    return o


MODELS = {
    # name: (builder, args)
    "gb":     dict(kind="cart", w=5.4, h=6.0, d=1.5, r=0.45, lw=4.0, lh=3.0, ly=0.2, notch=(1.2, 0.35), seg=10),
    "gbc":    dict(kind="cart", w=5.4, h=6.0, d=1.5, r=0.45, lw=4.0, lh=3.0, ly=0.2, notch=(1.2, 0.35), seg=10),
    "gba":    dict(kind="cart", w=5.6, h=3.6, d=1.5, r=0.35, lw=4.6, lh=2.7, ly=0.0, notch=(1.4, 0.3), seg=10),
    "n64":    dict(kind="cart", w=8.0, h=9.0, d=3.0, r=0.55, lw=5.8, lh=4.6, ly=0.6, grip=1.3, seg=10),
    "nes":    dict(kind="cart", w=7.2, h=9.8, d=2.8, r=0.35, lw=5.4, lh=4.6, ly=0.6, seg=7),
    "snes":   dict(kind="cart", w=8.6, h=5.8, d=2.6, r=0.5, lw=6.0, lh=4.2, ly=0.2, seg=9),
    "nds":    dict(kind="cart", w=3.6, h=3.7, d=0.95, r=0.28, lw=2.7, lh=2.5, ly=0.0, corner_cut=("tr", 0.7), seg=8),
    "3ds":    dict(kind="cart", w=3.6, h=3.7, d=0.95, r=0.28, lw=2.7, lh=2.5, ly=0.0, corner_cut=("tr", 0.7), seg=8),
    "switch": dict(kind="cart", w=3.2, h=3.2, d=0.8, r=0.2, lw=2.5, lh=2.4, ly=0.0, corner_cut=("tr", 0.6), seg=8),
    "vita":   dict(kind="cart", w=4.8, h=3.0, d=0.8, r=0.2, lw=3.8, lh=2.4, ly=0.0, seg=8),
    "psp":    dict(kind="disc", radius=3.4, thickness=0.6, label_radius=2.85, hole=0.5),
    "cd":     dict(kind="disc", radius=3.6, thickness=0.35, label_radius=3.3, hole=0.65),
    "default": dict(kind="cart", w=6.2, h=7.2, d=0.76, r=0.45, lw=5.7, lh=6.7, ly=0.0, seg=9),
    # horizontal cartridge for landscape box art
    "wide":    dict(kind="cart", w=7.6, h=5.6, d=0.76, r=0.45, lw=7.1, lh=5.1, ly=0.0, seg=9),
}

SYSTEM_MAP = {
    # one cuboid for normal art, a disc for CD consoles
    "GB": "default", "GBC": "default", "GBA": "default", "N64": "default",
    "NES": "default", "FC": "default", "SNES": "default", "SFC": "default",
    "NDS": "default", "3DS": "default", "SWITCH": "default",
    "VITA": "default", "VB": "default",
    "MD": "default", "MS": "default", "GG": "default", "GW": "default",
    "LYNX": "default", "NGP": "default", "NGPC": "default", "WSC": "default",
    "ATARI2600": "default", "ATARI7800": "default", "PICO8": "default",
    "MAME": "default", "MAME2003PLUS": "default", "MAME2010": "default",
    "FBNEO": "default", "ARCADE": "default", "PGM": "default",
    "CPS1": "default", "CPS2": "default", "CPS3": "default",
    "NEOGEO": "default",
    "JAVA": "default", "PORTS": "default", "OPENBOR": "default",
    "EASYRPG": "default",
    "PSP": "cd", "PPSSPP": "cd", "PS": "cd", "DC": "cd", "SS": "cd",
    "SEGACD": "cd", "PCE": "cd", "PCECD": "cd", "MEGACD": "cd",
}


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "assets/models"
    os.makedirs(outdir, exist_ok=True)
    for name, spec in MODELS.items():
        spec = dict(spec)
        kind = spec.pop("kind")
        if kind == "cart":
            o = build_cart(spec["w"], spec["h"], spec["d"], spec["r"],
                           spec["lw"], spec["lh"], spec.get("ly", 0.0),
                           spec.get("grip", 0.0),
                           spec.get("corner_cut"), spec.get("notch"),
                           seg=spec.get("seg", 8),
                           brand=spec.get("brand"))
        else:
            o = build_disc(spec["radius"], spec["thickness"],
                           spec["label_radius"], spec.get("hole", 0.55))
        path = os.path.join(outdir, f"{name}.obj")
        o.save(path)
        print(f"{path}: {len(o.v)} verts {len(o.f)} faces")

    with open(os.path.join(outdir, "map.txt"), "w") as fp:
        for sysid, model in sorted(SYSTEM_MAP.items()):
            fp.write(f"{sysid} {model}\n")
    print("wrote map.txt")


if __name__ == "__main__":
    main()
